/*******************************************************************************
*
*  (C) COPYRIGHT AUTHORS, 2015 - 2022
*
*  TITLE:       PROPSECURITYCONSTS.H
*
*  VERSION:     2.00
*
*  DATE:        19 Jun 2022
*
*  Consts header file for Security property sheet.
*
* THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
* ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED
* TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
* PARTICULAR PURPOSE.
*
*******************************************************************************/
#pragma once

/********************************************************************************
*
* Access values for supported types
*
*********************************************************************************/

#define SI_ACCESS_DEFAULT_FLAGS SI_ACCESS_GENERAL | SI_ACCESS_SPECIFIC

#define SI_ACCESS_DEFAULT_ENTRY(Access, Name) { &GUID_NULL, Access, Name, SI_ACCESS_DEFAULT_FLAGS }

//
//General Access Values
//
#define MAX_KNOWN_GENERAL_ACCESS_VALUE 5
static SI_ACCESS GeneralAccessValues[MAX_KNOWN_GENERAL_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(DELETE, L"删除"),
    SI_ACCESS_DEFAULT_ENTRY(READ_CONTROL, L"读取控制"),
    SI_ACCESS_DEFAULT_ENTRY(WRITE_DAC, L"写入 DAC"),
    SI_ACCESS_DEFAULT_ENTRY(WRITE_OWNER, L"读取所有者"),
    SI_ACCESS_DEFAULT_ENTRY(SYNCHRONIZE, L"同步")
};

//
//Section Access Values
//
#define MAX_KNOWN_SECTION_ACCESS_VALUE 5
static SI_ACCESS SectionAccessValues[MAX_KNOWN_SECTION_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(SECTION_QUERY, L"查询"),
    SI_ACCESS_DEFAULT_ENTRY(SECTION_MAP_WRITE, L"映射写入"),
    SI_ACCESS_DEFAULT_ENTRY(SECTION_MAP_READ, L"映射读取"),
    SI_ACCESS_DEFAULT_ENTRY(SECTION_MAP_EXECUTE, L"映射执行"),
    SI_ACCESS_DEFAULT_ENTRY(SECTION_EXTEND_SIZE, L"扩展大小")
};

//
//Directory Access Values
//
#define MAX_KNOWN_DIRECTORY_ACCESS_VALUE 4
static SI_ACCESS DirectoryAccessValues[MAX_KNOWN_DIRECTORY_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(DIRECTORY_QUERY, L"查询"),
    SI_ACCESS_DEFAULT_ENTRY(DIRECTORY_TRAVERSE, L"遍历"),
    SI_ACCESS_DEFAULT_ENTRY(DIRECTORY_CREATE_OBJECT, L"创建对象"),
    SI_ACCESS_DEFAULT_ENTRY(DIRECTORY_CREATE_SUBDIRECTORY, L"创建子目录")
};

//
//File Access Values
//
#define MAX_KNOWN_FILE_ACCESS_VALUE 14
static SI_ACCESS FileAccessValues[MAX_KNOWN_FILE_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(FILE_READ_DATA, L"读取数据"),
    SI_ACCESS_DEFAULT_ENTRY(FILE_LIST_DIRECTORY, L"列举目录"),
    SI_ACCESS_DEFAULT_ENTRY(FILE_WRITE_DATA, L"写入数据"),
    SI_ACCESS_DEFAULT_ENTRY(FILE_ADD_FILE, L"创建文件"),
    SI_ACCESS_DEFAULT_ENTRY(FILE_APPEND_DATA, L"追加数据"),
    SI_ACCESS_DEFAULT_ENTRY(FILE_ADD_SUBDIRECTORY, L"创建子目录"),
    SI_ACCESS_DEFAULT_ENTRY(FILE_CREATE_PIPE_INSTANCE, L"创建管道实例"),
    SI_ACCESS_DEFAULT_ENTRY(FILE_READ_EA, L"读取 EA"),
    SI_ACCESS_DEFAULT_ENTRY(FILE_WRITE_EA, L"写入 EA"),
    SI_ACCESS_DEFAULT_ENTRY(FILE_EXECUTE, L"执行"),
    SI_ACCESS_DEFAULT_ENTRY(FILE_TRAVERSE, L"遍历"),
    SI_ACCESS_DEFAULT_ENTRY(FILE_DELETE_CHILD, L"删除子项"),
    SI_ACCESS_DEFAULT_ENTRY(FILE_READ_ATTRIBUTES, L"读取属性"),
    SI_ACCESS_DEFAULT_ENTRY(FILE_WRITE_ATTRIBUTES, L"写入属性")
};

//
//Event Access Values
//
#define MAX_KNOWN_EVENT_ACCESS_VALUE 2
static SI_ACCESS EventAccessValues[MAX_KNOWN_EVENT_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(EVENT_QUERY_STATE, L"查询状态"),
    SI_ACCESS_DEFAULT_ENTRY(EVENT_MODIFY_STATE, L"修改状态")
};

//
//Mutant Access Values
//
#define MAX_KNOWN_MUTANT_ACCESS_VALUE 1
static SI_ACCESS MutantAccessValues[MAX_KNOWN_MUTANT_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(MUTANT_QUERY_STATE, L"查询状态")
};

//
//Desktop Access Values
//
#define MAX_KNOWN_DESKTOP_ACCESS_VALUE 9
static SI_ACCESS DesktopAccessValues[MAX_KNOWN_DESKTOP_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(DESKTOP_READOBJECTS, L"读取对象"),
    SI_ACCESS_DEFAULT_ENTRY(DESKTOP_CREATEWINDOW, L"创建窗口"),
    SI_ACCESS_DEFAULT_ENTRY(DESKTOP_CREATEMENU, L"创建菜单"),
    SI_ACCESS_DEFAULT_ENTRY(DESKTOP_HOOKCONTROL, L"挂钩控制"),
    SI_ACCESS_DEFAULT_ENTRY(DESKTOP_JOURNALRECORD, L"记录日志"),
    SI_ACCESS_DEFAULT_ENTRY(DESKTOP_JOURNALPLAYBACK, L"回放日志"),
    SI_ACCESS_DEFAULT_ENTRY(DESKTOP_ENUMERATE, L"枚举"),
    SI_ACCESS_DEFAULT_ENTRY(DESKTOP_WRITEOBJECTS, L"写入对象"),
    SI_ACCESS_DEFAULT_ENTRY(DESKTOP_SWITCHDESKTOP, L"切换桌面")
};

//
//WinStation Access Values
//
#define MAX_KNOWN_WINSTATION_ACCESS_VALUE 9
static SI_ACCESS WinStationAccessValues[MAX_KNOWN_WINSTATION_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(WINSTA_ENUMDESKTOPS, L"枚举桌面"),
    SI_ACCESS_DEFAULT_ENTRY(WINSTA_READATTRIBUTES, L"读取属性"),
    SI_ACCESS_DEFAULT_ENTRY(WINSTA_ACCESSCLIPBOARD, L"访问剪切板"),
    SI_ACCESS_DEFAULT_ENTRY(WINSTA_CREATEDESKTOP, L"创建桌面"),
    SI_ACCESS_DEFAULT_ENTRY(WINSTA_WRITEATTRIBUTES, L"写入属性"),
    SI_ACCESS_DEFAULT_ENTRY(WINSTA_ACCESSGLOBALATOMS, L"访问全局原子表项"),
    SI_ACCESS_DEFAULT_ENTRY(WINSTA_EXITWINDOWS, L"退出窗口"),
    SI_ACCESS_DEFAULT_ENTRY(WINSTA_ENUMERATE, L"枚举"),
    SI_ACCESS_DEFAULT_ENTRY(WINSTA_READSCREEN, L"读取屏幕")
};

//
//Key Access Values
//
#define MAX_KNOWN_KEY_ACCESS_VALUE 8
static SI_ACCESS KeyAccessValues[MAX_KNOWN_KEY_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(KEY_QUERY_VALUE, L"查询数值"),
    SI_ACCESS_DEFAULT_ENTRY(KEY_SET_VALUE, L"设置数值"),
    SI_ACCESS_DEFAULT_ENTRY(KEY_CREATE_SUB_KEY, L"创建子键"),
    SI_ACCESS_DEFAULT_ENTRY(KEY_ENUMERATE_SUB_KEYS, L"枚举子键"),
    SI_ACCESS_DEFAULT_ENTRY(KEY_NOTIFY, L"通知"),
    SI_ACCESS_DEFAULT_ENTRY(KEY_CREATE_LINK, L"创建链接"),
    SI_ACCESS_DEFAULT_ENTRY(KEY_WOW64_64KEY, L"访问 64 位键"),
    SI_ACCESS_DEFAULT_ENTRY(KEY_WOW64_32KEY, L"访问 32 位键")
};

//
//Semaphore Access Values
//
#define MAX_KNOWN_SEMAPHORE_ACCESS_VALUE 2
static SI_ACCESS SemaphoreAccessValues[MAX_KNOWN_SEMAPHORE_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(SEMAPHORE_QUERY_STATE, L"查询状态"),
    SI_ACCESS_DEFAULT_ENTRY(SEMAPHORE_MODIFY_STATE, L"修改状态")
};

//
//Symlink Access Values
//
#define MAX_KNOWN_SYMLINK_ACCESS_VALUE 2
static SI_ACCESS SymlinkAccessValues[MAX_KNOWN_SYMLINK_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(SYMBOLIC_LINK_QUERY, L"链接查询"),
    SI_ACCESS_DEFAULT_ENTRY(SYMBOLIC_LINK_SET, L"链接集")
};

//
//Timer Access Values
//
#define MAX_KNOWN_TIMER_ACCESS_VALUE 2
static SI_ACCESS TimerAccessValues[MAX_KNOWN_TIMER_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(TIMER_QUERY_STATE, L"查询状态"),
    SI_ACCESS_DEFAULT_ENTRY(TIMER_MODIFY_STATE, L"修改状态")
};

//
//Job Access Values
//
#define MAX_KNOWN_JOB_ACCESS_VALUE 5
static SI_ACCESS JobAccessValues[MAX_KNOWN_JOB_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(JOB_OBJECT_ASSIGN_PROCESS, L"分配进程"),
    SI_ACCESS_DEFAULT_ENTRY(JOB_OBJECT_SET_ATTRIBUTES, L"设置属性"),
    SI_ACCESS_DEFAULT_ENTRY(JOB_OBJECT_QUERY, L"查询"),
    SI_ACCESS_DEFAULT_ENTRY(JOB_OBJECT_TERMINATE, L"终止"),
    SI_ACCESS_DEFAULT_ENTRY(JOB_OBJECT_SET_SECURITY_ATTRIBUTES, L"设置安全属性")
};

//
//Port Access Values
//
#define MAX_KNOWN_PORT_ACCESS_VALUE 1
static SI_ACCESS PortAccessValues[MAX_KNOWN_PORT_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(PORT_CONNECT, L"连接")
};

//
//Session Access Values
//
#define MAX_KNOWN_SESSION_ACCESS_VALUE 2
static SI_ACCESS SessionAccessValues[MAX_KNOWN_SESSION_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(SESSION_QUERY_ACCESS, L"查询"),
    SI_ACCESS_DEFAULT_ENTRY(SESSION_MODIFY_ACCESS, L"修改")
};

//
//IoCompletion Access Values
//
#define MAX_KNOWN_IOCOMPLETION_ACCESS_VALUE 2
static SI_ACCESS IoCompletionAccessValues[MAX_KNOWN_IOCOMPLETION_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(IO_COMPLETION_QUERY_STATE, L"查询状态"),
    SI_ACCESS_DEFAULT_ENTRY(IO_COMPLETION_MODIFY_STATE, L"修改状态")
};

//
//MemoryPartition Access Values
//
#define MAX_KNOWN_MEMORYPARTITION_ACCESS_VALUE 2
static SI_ACCESS MemoryPartitionAccessValues[MAX_KNOWN_MEMORYPARTITION_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(MEMORY_PARTITION_QUERY_ACCESS, L"查询"),
    SI_ACCESS_DEFAULT_ENTRY(MEMORY_PARTITION_MODIFY_ACCESS, L"修改")
};

//
//Process Access Values
//
#define MAX_KNOWN_PROCESS_ACCESS_VALUE 14
static SI_ACCESS ProcessAccessValues[MAX_KNOWN_PROCESS_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(PROCESS_TERMINATE, L"终止"),
    SI_ACCESS_DEFAULT_ENTRY(PROCESS_CREATE_THREAD, L"创建线程"),
    SI_ACCESS_DEFAULT_ENTRY(PROCESS_SET_SESSIONID, L"设置会话 ID"),
    SI_ACCESS_DEFAULT_ENTRY(PROCESS_VM_OPERATION, L"操作虚拟内存"),
    SI_ACCESS_DEFAULT_ENTRY(PROCESS_VM_READ, L"读取虚拟内存"),
    SI_ACCESS_DEFAULT_ENTRY(PROCESS_VM_WRITE, L"写入虚拟内存"),
    SI_ACCESS_DEFAULT_ENTRY(PROCESS_DUP_HANDLE, L"复制句柄"),
    SI_ACCESS_DEFAULT_ENTRY(PROCESS_CREATE_PROCESS, L"创建进程"),
    SI_ACCESS_DEFAULT_ENTRY(PROCESS_SET_QUOTA, L"设置配额"),
    SI_ACCESS_DEFAULT_ENTRY(PROCESS_SET_INFORMATION, L"设置信息"),
    SI_ACCESS_DEFAULT_ENTRY(PROCESS_QUERY_INFORMATION, L"查询信息"),
    SI_ACCESS_DEFAULT_ENTRY(PROCESS_SUSPEND_RESUME, L"挂起/恢复"),
    SI_ACCESS_DEFAULT_ENTRY(PROCESS_QUERY_LIMITED_INFORMATION, L"查询受限信息"),
    SI_ACCESS_DEFAULT_ENTRY(PROCESS_SET_LIMITED_INFORMATION, L"设置受限信息")
};

//
//Thread Access Values
//
#define MAX_KNOWN_THREAD_ACCESS_VALUE 13
static SI_ACCESS ThreadAccessValues[MAX_KNOWN_THREAD_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(THREAD_TERMINATE, L"终止"),
    SI_ACCESS_DEFAULT_ENTRY(THREAD_SUSPEND_RESUME, L"挂起/恢复"),
    SI_ACCESS_DEFAULT_ENTRY(THREAD_ALERT, L"警告"),
    SI_ACCESS_DEFAULT_ENTRY(THREAD_GET_CONTEXT, L"获取上下文"),
    SI_ACCESS_DEFAULT_ENTRY(THREAD_SET_CONTEXT, L"设置上下文"),
    SI_ACCESS_DEFAULT_ENTRY(THREAD_QUERY_INFORMATION, L"查询信息"),
    SI_ACCESS_DEFAULT_ENTRY(THREAD_SET_INFORMATION, L"设置信息"),
    SI_ACCESS_DEFAULT_ENTRY(THREAD_SET_THREAD_TOKEN, L"设置线程令牌"),
    SI_ACCESS_DEFAULT_ENTRY(THREAD_IMPERSONATE, L"模拟"),
    SI_ACCESS_DEFAULT_ENTRY(THREAD_DIRECT_IMPERSONATION, L"直接模拟"),
    SI_ACCESS_DEFAULT_ENTRY(THREAD_SET_LIMITED_INFORMATION, L"设置受限信息"),
    SI_ACCESS_DEFAULT_ENTRY(THREAD_QUERY_LIMITED_INFORMATION, L"查询受限信息"),
    SI_ACCESS_DEFAULT_ENTRY(THREAD_RESUME, L"恢复")
};

//
//Token Access Values
//
#define MAX_KNOWN_TOKEN_ACCESS_VALUE 9

static SI_ACCESS TokenAccessValues[MAX_KNOWN_TOKEN_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(TOKEN_ASSIGN_PRIMARY, L"分配主令牌"),
    SI_ACCESS_DEFAULT_ENTRY(TOKEN_DUPLICATE, L"复制"),
    SI_ACCESS_DEFAULT_ENTRY(TOKEN_IMPERSONATE, L"模拟"),
    SI_ACCESS_DEFAULT_ENTRY(TOKEN_QUERY, L"查询"),
    SI_ACCESS_DEFAULT_ENTRY(TOKEN_QUERY_SOURCE, L"查询源"),
    SI_ACCESS_DEFAULT_ENTRY(TOKEN_ADJUST_PRIVILEGES, L"修改权限"),
    SI_ACCESS_DEFAULT_ENTRY(TOKEN_ADJUST_GROUPS, L"修改组"),
    SI_ACCESS_DEFAULT_ENTRY(TOKEN_ADJUST_DEFAULT, L"修改默认值"),
    SI_ACCESS_DEFAULT_ENTRY(TOKEN_ADJUST_SESSIONID, L"修改会话 ID")
};

#define MAX_KNOWN_TRANSACTION_ACCESS_VALUE 7
static SI_ACCESS TransactionAccessValues[MAX_KNOWN_TRANSACTION_ACCESS_VALUE] = {
    SI_ACCESS_DEFAULT_ENTRY(TRANSACTION_QUERY_INFORMATION, L"查询信息"),
    SI_ACCESS_DEFAULT_ENTRY(TRANSACTION_SET_INFORMATION, L"设置信息"),
    SI_ACCESS_DEFAULT_ENTRY(TRANSACTION_ENLIST, L"添加"),
    SI_ACCESS_DEFAULT_ENTRY(TRANSACTION_COMMIT, L"提交"),
    SI_ACCESS_DEFAULT_ENTRY(TRANSACTION_ROLLBACK, L"回滚"),
    SI_ACCESS_DEFAULT_ENTRY(TRANSACTION_PROPAGATE, L"传播"),
    SI_ACCESS_DEFAULT_ENTRY(TRANSACTION_RIGHT_RESERVED1, L"保留权限 1")
};
