//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDS_DESC_DEVICE                 100
#define IDS_DESC_DRIVER                 101
#define IDR_MAINMENU                    101
#define IDS_DESC_SECTION                102
#define IDS_DESC_PORT                   103
#define IDS_DESC_SYMLINK                104
#define IDS_DESC_KEY                    105
#define IDS_DESC_EVENT                  106
#define IDS_DESC_JOB                    107
#define IDS_DESC_MUTANT                 108
#define IDS_DESC_KEYEDEVENT             109
#define IDS_DESC_TYPE                   110
#define IDS_DESC_DIRECTORY              111
#define IDS_DESC_WINSTATION             112
#define IDS_DESC_CALLBACK               113
#define IDS_DESC_SEMAPHORE              114
#define IDS_DESC_WAITABLEPORT           115
#define IDS_DESC_TIMER                  116
#define IDS_DESC_SESSION                117
#define IDS_DESC_CONTROLLER             118
#define IDS_DESC_PROFILE                119
#define IDS_DESC_EVENTPAIR              120
#define IDS_DESC_DESKTOP                121
#define IDS_DESC_FILE                   122
#define IDS_DESC_WMIGUID                123
#define IDS_DESC_DEBUGOBJECT            124
#define IDS_DESC_IOCOMPLETION           125
#define IDS_DESC_PROCESS                126
#define IDS_DESC_ADAPTER                127
#define ID_ABOUT_ICON                   128
#define IDS_DESC_TOKEN                  128
#define IDS_DESC_ETWREGISTRATION        129
#define IDS_DESC_THREAD                 130
#define IDS_DESC_TMTX                   131
#define IDS_DESC_TMTM                   132
#define IDS_DESC_TMRM                   133
#define IDS_DESC_TMEN                   134
#define IDS_DESC_PCWOBJECT              135
#define IDS_DESC_FLT_CONN_PORT          136
#define IDS_DESC_FLT_COMM_PORT          137
#define IDS_DESC_POWERREQUEST           138
#define IDS_DESC_ETWCONSUMER            139
#define IDS_DESC_TPWORKERFACTORY        140
#define IDS_DESC_COMPOSITION            141
#define IDS_DESC_IRTIMER                142
#define IDS_DESC_DXGKSHAREDRES          143
#define IDS_DESC_DXGK_SHARED_RESOURCE   143
#define IDS_DESC_DXGK_SHARED_SWAPCHAIN  144
#define IDS_DESC_DXGK_SHARED_SYNC       145
#define IDS_DESC_DXGK_CURRENT_DXG_PROCESS_OBJECT 146
#define IDS_DESC_DXGK_DISPLAY_MANAGER_OBJECT 147
#define IDS_DESC_DXGK_SHARED_BUNDLE_OBJECT 148
#define IDS_DESC_DXGK_SHARED_PROTECTED_SESSION_OBJECT 149
#define IDS_DESC_DXGK_COMPOSITION_OBJECT 150
#define IDS_DESC_DXGK_SHARED_KEYED_MUTEX_OBJECT 151
#define IDS_DESC_MEMORY_PARTITION       152
#define IDS_DESC_REGISTRY_TRANSACTION   153
#define IDS_DESC_DMAADAPTER             154
#define IDS_DESC_DMACONTROLLER          155
#define IDS_DESC_DMADOMAIN              155
#define IDS_DESC_DXGK_CURRENT_DXG_THREAD_OBJECT 156
#define IDS_DESC_COVERAGESAMPLER        157
#define IDS_DESC_ACTIVATIONOBJECT       158
#define IDS_DESC_ACTIVITYREFERENCE      159
#define IDS_DESC_COREMESSAGING          160
#define IDS_DESC_RAWINPUTMANAGER        161
#define IDS_DESC_WAITCOMPLETIONPACKET   162
#define IDS_DESC_IOCOMPLETIONRESERVE    163
#define IDD_DIALOG_ABOUT                164
#define IDS_DESC_USERAPCRESERVE         164
#define IDB_BITMAP1                     165
#define IDS_DESC_IORING                 165
#define IDR_ACCELERATOR1                166
#define IDS_DESC_TERMINAL               166
#define IDD_DIALOG_SEARCH               167
#define IDS_DESC_TERMINALEVENTQUEUE     167
#define IDS_DESC_ENERGYTRACKER          168
#define IDS_DESC_DXGK_DISPLAYMUXSWITCH  169
#define IDR_KDBGDRV                     170
#define IDS_DESC_VREGCFGCTX             170
#define IDD_PROP_BASIC                  171
#define IDS_DESC_PSSILOCONTEXTNP        171
#define IDD_PROP_PROCESSLIST            172
#define IDS_DESC_PSSILOCONTEXT          172
#define IDD_PROP_SERVICE                173
#define IDS_DESC_ETWSESSIONDEMUXENTRY   173
#define IDI_ICON_MAIN                   174
#define IDD_PROP_SYMLINK                174
#define IDS_DESC_NDISCMSTATE            174
#define IDD_PROP_SECTION                175
#define IDS_DESC_PROCESSSTATECHANGE     175
#define IDD_PROP_SEMAPHORE              176
#define IDS_DESC_THREADSTATECHANGE      176
#define IDD_PROP_EVENT                  177
#define IDS_DESC_CROSSVMEVENT           177
#define IDD_PROP_MUTANT                 178
#define IDS_DESC_CROSSVMMUTANT          178
#define IDD_PROP_TIMER                  179
#define IDS_DESC_SCHEDULERSHAREDDATA    179
#define IDD_PROP_KEY                    180
#define IDS_DESC_CPUPARTITION           180
#define IDD_PROP_JOB                    181
#define IDS_STRING181                   181
#define IDS_DESC_VIRTUALKEY             181
#define IDD_PROP_WINSTATION             183
#define IDD_PROP_DRIVER                 184
#define IDD_PROP_DEVICE                 185
#define IDD_PROP_OBJECTDUMP             186
#define IDD_PROP_TYPE                   187
#define IDD_PROP_DESKTOPS               189
#define IDD_PROP_IOCOMPLETION           190
#define IDD_PROP_PIPE                   192
#define IDD_DIALOG_USD                  193
#define IDD_DIALOG_PNAMESPACE           194
#define IDD_DIALOG_EXTRASLIST           195
#define IDD_DIALOG_IPCOBJECTS           196
#define IDD_PROP_MAILSLOT               197
#define IDD_PROP_ALPCPORT               198
#define IDI_ICON_VIEW_DEFAULT           207
#define IDI_ICON_VIEW_SELECTED          208
#define IDI_ICON_PIPE                   213
#define IDI_ICON_MAILSLOT               214
#define IDD_DIALOG_CALLBACKS            241
#define IDD_DIALOG_PSLIST               242
#define IDI_ICON_HALDMA                 243
#define IDD_PROP_PROCESS                243
#define IDD_PROP_THREAD                 244
#define IDD_DIALOG_TOKEN                245
#define IDD_DIALOG_SLCACHE              246
#define IDD_DIALOG_GLOBALS              247
#define IDD_PROP_TOKEN                  248
#define IDD_DIALOG_LOGVIEWER            249
#define IDD_DIALOG_VIEWPLUGINS          251
#define IDI_ICON1                       254
#define IDI_ICON_SECURITY               254
#define IDD_DIALOG_VIEWSD               255
#define IDD_DIALOG_SDVIEW               255
#define IDD_PROP_PROCESSLIST1           256
#define IDD_PROP_PORTLIST               256
#define IDD_PROP_ALPCPORTLIST           256
#define IDD_DIALOG_LOADLIST             257
#define IDD_DIALOG_STATS                260
#define IDD_DIALOG_PROGRESS             262
#define IDR_PSLISTMENU                  264
#define IDD_DIALOG1                     265
#define IDD_DIALOG_PSLISTLEGEND         265
#define IDI_ICON_DEVICE                 300
#define IDS_DESC_UNKNOWN                300
#define IDI_ICON_DRIVER                 301
#define IDI_ICON_SECTION                302
#define IDI_ICON_PORT                   303
#define IDI_ICON_SYMLINK                304
#define IDI_ICON_KEY                    305
#define IDI_ICON_EVENT                  306
#define IDI_ICON_JOB                    307
#define IDI_ICON_MUTANT                 308
#define IDI_ICON_KEYEDEVENT             309
#define IDI_ICON_TYPE                   310
#define IDI_ICON_DIRECTORY              311
#define IDI_ICON_WINSTATION             312
#define IDI_ICON_CALLBACK               313
#define IDI_ICON_SEMAPHORE              314
#define IDI_ICON_WAITABLEPORT           315
#define IDI_ICON_TIMER                  316
#define IDI_ICON_SESSION                317
#define IDI_ICON_CONTROLLER             318
#define IDI_ICON_PROFILE                319
#define IDI_ICON_EVENTPAIR              320
#define IDI_ICON_DESKTOP                321
#define IDI_ICON_FILE                   322
#define IDI_ICON_WMIGUID                323
#define IDI_ICON_DEBUGOBJECT            324
#define IDI_ICON_IOCOMPLETION           325
#define IDI_ICON_PROCESS                326
#define IDI_ICON_ADAPTER                327
#define IDI_ICON_TOKEN                  328
#define IDI_ICON_ETWREGISTRATION        329
#define IDI_ICON_THREAD                 330
#define IDI_ICON_TMTX                   331
#define IDI_ICON_TMTM                   332
#define IDI_ICON_TMRM                   333
#define IDI_ICON_TMEN                   334
#define IDI_ICON_PCWOBJECT              335
#define IDI_ICON_FLTCONNPORT            336
#define IDI_ICON_FLTCOMMPORT            337
#define IDI_ICON_POWERREQUEST           338
#define IDI_ICON_ETWCONSUMER            339
#define IDI_ICON_TPWORKERFACTORY        340
#define IDI_ICON_COMPOSITION            341
#define IDI_ICON_IRTIMER                342
#define IDI_ICON_DXOBJECT               343
#define IDI_ICON_MEMORYPARTITION        350
#define IDI_ICON_UNKNOWN                352
#define IDC_OBJECT_FLAGS                700
#define ID_DEVICEDESCRIPTION            1001
#define ID_SECTION_ATTR                 1002
#define IDC_TYPE_FLAGS                  1002
#define ID_SECTIONSIZE                  1003
#define ID_SEMAPHORECURRENT             1004
#define IDC_JOB_PLIST                   1004
#define ID_IMAGE_ENTRY                  1005
#define ID_SEMAPHOREMAXCOUNT            1006
#define ID_DESKTOPSNOTALL               1006
#define ID_DESKTOPSLIST                 1007
#define ID_EVENTTYPE                    1008
#define IDC_QUERYFAIL                   1008
#define ID_EVENTSTATE                   1009
#define IDC_SERVICE_DEPENDSONGROUP      1009
#define ID_IMAGE_STACKRESERVE           1010
#define IDC_SERVICE_DEPENDSONSERVICE    1010
#define ID_MUTANTABANDONED              1011
#define IDC_SERVICE_DEPENDENTSERVICES   1011
#define ID_IMAGE_STACKCOMMIT            1012
#define IDC_SERVICE_DESCRIPTION         1012
#define ID_IMAGE_SUBSYSTEM              1013
#define ID_MUTANTSTATE                  1014
#define IDC_SERVICE_IMAGEPATH           1014
#define ID_IMAGE_MJV                    1015
#define IDC_SERVICE_DISPLAYNAME         1015
#define ID_IOCOMPLETIONSTATE            1015
#define ID_OBJECT_SYMLINK_CREATION      1016
#define IDC_SERVICE_KEYNAME             1016
#define IDC_SERVICE_KEYNAME2            1017
#define IDC_SERVICE_LOADORDERGROUP      1017
#define ID_USDLIST                      1017
#define ID_OBJECT_SYMLINK_TARGET        1018
#define ID_NAMESPACELIST                1018
#define ID_IMAGE_MNV                    1019
#define ID_PNAMESPACESNOTALL            1019
#define ID_PNAMESPACESINFO              1019
#define ID_TIMERREMAINING               1020
#define ID_IMAGE_MNV2                   1020
#define ID_IMAGE_FLAGS                  1020
#define ID_IMAGE_EXECUTABLE             1021
#define ID_EXTRASLIST                   1021
#define ID_TIMERSTATE                   1022
#define IDC_PSLIST_STATUSBAR            1022
#define ID_KEYSUBKEYS                   1023
#define ID_IPCOBJECTSLIST               1023
#define ID_KEYLASTWRITE                 1024
#define ID_IPCROOT                      1024
#define ID_KEYVALUES                    1025
#define ID_MAILSLOT_FULLPATH            1025
#define ID_JOBTOTALPROCS                1026
#define ID_MAILSLOT_MAXMESSAGESZ        1026
#define ID_JOBACTIVEPROCS               1027
#define ID_MAILSLOT_QUOTA               1027
#define ID_JOBTERMINATEDPROCS           1028
#define ID_MAILSLOT_NEXTMSGSZ           1028
#define ID_MAILSLOT_READTIMEOUT         1029
#define ID_JOBTOTALUMTIME               1030
#define ID_MAILSLOT_MSGAVAILABLE        1030
#define ID_JOBTOTALKMTIME               1032
#define ID_JOBTPTOTALKMTIME             1033
#define ID_JOBTOTALPF                   1034
#define ID_SIZEOFBOUNDARYINFO           1035
#define ID_JOBTPTOTALKMTIME2            1035
#define ID_JOBTPTOTALUMTIME             1035
#define ID_INTEGRITYLABEL               1036
#define ID_TYPE_COUNT                   1037
#define ID_BDESCRIPTOR_ENTRIES          1037
#define ID_TYPE_HANDLECOUNT             1038
#define ID_TYPE_PEAKCOUNT               1039
#define ID_BDESCRIPTOR_NAME2            1039
#define ID_TYPE_PEAKHANDLECOUNT         1040
#define ID_BDESCRIPTOR_SID_COPY         1040
#define ID_TYPE_POOLTYPE                1041
#define IDC_ABOUT_GLOBALS               1041
#define ID_ALPC_OWNERPROCESS            1043
#define IDC_LOADING_MSG                 1044
#define ID_TYPE_ACL_LIST                1045
#define IDC_PSLIST_LISTVIEW             1045
#define IDC_LOADING_MSG2                1045
#define ID_TYPE_ATTRLIST                1046
#define IDC_GLOBALS_COPY                1046
#define IDC_PSLIST_TREELIST             1047
#define ID_SEARCH_STATUSBAR             1048
#define ID_EXTRASLIST_STATUSBAR         1049
#define ID_PROCESSINFO                  1050
#define ID_THREADINFO                   1051
#define ID_OBJECT_NAME                  1053
#define ID_OBJECT_TYPE                  1054
#define ID_OBJECT_REFC                  1056
#define ID_OBJECT_HANDLES               1057
#define ID_OBJECT_PP_CHARGE             1058
#define ID_OBJECT_NP_CHARGE             1059
#define ID_OBJECT_TRUSTLABEL            1060
#define IDC_PROCESS_STARTED             1060
#define ID_OBJECT_SYMLINKINFO           1061
#define ID_SECTIONINFO                  1061
#define ID_SEMAPHOREINFO                1061
#define ID_WINSTATIONINFO               1061
#define IDC_PROCESS_CMDLINE             1061
#define IDC_PROCESS_CURDIR              1062
#define ID_PIPE_CURINSTANCES            1063
#define IDC_PROCESS_FILENAME            1063
#define ID_OBJECT_HEADER                1064
#define ID_TYPE_PPCHARGE                1065
#define IDC_PROCESS_IMAGETYPE           1065
#define IDC_THREAD_NAME                 1065
#define IDC_PROCESS_BROWSE              1066
#define ID_PIPE_MAXINSTANCES            1067
#define IDC_PROCESS_MITIGATIONS         1067
#define ID_OBJECT_ADDR                  1068
#define ID_PIPE_QUERYFAIL               1068
#define IDC_PROCESS_STARTED2            1069
#define IDC_PROCESS_PROTECTION          1069
#define IDC_THREAD_STARTED              1069
#define IDC_PROCESS_TYPE_FLAGS          1070
#define IDC_THREAD_KERNELTIME           1070
#define IDC_TOKEN_PRIVLIST              1070
#define IDC_PROCESS_CRITICAL            1071
#define IDC_THREAD_USERTIME             1071
#define IDC_TOKEN_ERROR                 1071
#define ID_TYPE_NPCHARGE                1072
#define IDC_THREAD_CONTEXTSWITCHES      1072
#define IDC_TOKEN_USER                  1072
#define IDC_THREAD_BASEPRIORITY         1073
#define IDC_TOKEN_                      1073
#define IDC_TOKEN_SID                   1073
#define IDC_THREAD_DYNPRIORITY          1074
#define IDC_TOKEN_SESSION               1074
#define IDC_THREAD_AFFINITYMASK         1075
#define IDC_THREAD_IDEALPROCESSOR       1075
#define IDC_TOKEN_ELEVATED              1075
#define IDC_THREAD_CRITICAL             1076
#define IDC_TOKEN_VIRTUALIZED           1076
#define IDC_TOKEN_INTEGRITYLEVEL        1077
#define IDC_TOKEN_UIACCESS              1078
#define IDC_TOKEN_APPCONTAINER          1079
#define ID_SLCACHELIST                  1080
#define IDC_TOKEN_AUTHID                1080
#define ID_TYPE_DESCRIPTION             1081
#define ID_SLCACHEINFO                  1081
#define ID_IMAGEINFO                    1082
#define ID_DEVICEINFO                   1082
#define ID_DRIVERINFO                   1082
#define ID_SLCACHELIST2                 1082
#define ID_SLDATALIST                   1082
#define IDC_SLVALUE                     1083
#define ID_IMAGE_STACKRESERVELABEL      1084
#define IDC_SLVALUE_VIEWWITH            1084
#define ID_IMAGE_STACKCOMMITLABEL       1085
#define ID_SLDESCRIPTOR_SIZE            1085
#define ID_IMAGE_EXECUTABLELABEL        1086
#define ID_SLDESCRIPTOR_DATALENGTH      1086
#define ID_IMAGE_SUBSYSLABEL            1087
#define ID_SLDESCRIPTOR_ATTRIBUTES      1087
#define ID_IMAGE_MJVLABEL               1088
#define ID_SLDESCRIPTOR_TYPE            1088
#define ID_IMAGE_MNVLABEL               1089
#define IDC_SLVALUE_NAME                1089
#define IDC_GLOBALS                     1089
#define ID_WINSTATIONVISIBLE            1090
#define IDC_SYSINFO                     1090
#define IDC_TOKEN_ADVANCED              1091
#define IDC_TOKEN_ADVANCED2             1092
#define IDC_TOKEN_LINKED                1092
#define ID_IMAGE_ENTRYLABEL             1093
#define IDC_TOKEN_ATTRLIST              1093
#define IDC_PLUGINLIST                  1094
#define IDC_SDVIEW_LIST                 1094
#define IDC_GLOBALS_CLOSE               1096
#define IDC_CANCEL                      1096
#define ID_PIPE_FULLPATH                1097
#define ID_PIPE_INBUFFER                1098
#define ID_PIPE_OUTBUFFER               1099
#define IDC_LOGLIST                     1099
#define ID_PIPE_TYPEMODE                1100
#define IDC_IMAGE_SERVICE_PROCES        1100
#define IDC_PCTL_SERVICE_PROCES         1100
#define ID_PIPE_ACCESSMODE              1101
#define IDC_IMAGE_PROTECTED_PROCESS     1101
#define IDC_PCTL_PROTECTED_PROCESS      1101
#define ID_PROCESSLIST                  1102
#define IDC_IMAGE_USER_PROCESS          1102
#define IDC_PCTL_USERPROCESS            1102
#define ID_PROCESSLISTNOALL             1103
#define ID_PIPE_WRITEQUOTAAVAIL         1103
#define IDC_PLUGIN_DESC                 1103
#define IDC_PLUGIN_FILENAME             1104
#define IDC_IMAGE_IMMERSIVE_PROCESS     1104
#define IDC_PCTL_IMMERSIVE_PROCESS      1104
#define IDC_PLUGIN_ADMIN                1105
#define ID_SEARCH_FIND                  1106
#define IDC_PLUGIN_OBJECTTYPE           1106
#define IDC_PLUGIN_DRIVER               1107
#define IDC_LIST                        1107
#define ID_SEARCH_NAME                  1108
#define IDC_PLUGIN_WINE                 1108
#define IDC_SDVIEW_OWNER                1108
#define ID_SEARCH_TYPE                  1109
#define IDC_PLUGIN_MINSTANCES           1109
#define ID_SEARCH_LIST                  1110
#define IDC_SDVIEW_STATUSBAR            1110
#define ID_ALPCLISTNOALL                1111
#define ID_ALPCLISTMSG                  1111
#define ID_SEARCH_GROUPBOX              1112
#define ID_ALPCLIST                     1112
#define ID_SEARCH_GROUPBOXOPTIONS       1113
#define ID_SEARCH_TYPELABEL             1114
#define IDC_EDIT1                       1115
#define IDC_SLSEARCH                    1115
#define IDC_SYSLINK1                    1116
#define IDC_ABOUT_SYSLINK               1116
#define IDC_STATS_TOTALHEAPALLOC        1117
#define IDC_STATS_TOTALHEAPFREE         1118
#define IDC_STATS_TOTALHEAPSCREATED     1119
#define IDC_STATS_TOTALHEAPSDESTROYED   1120
#define ID_DRIVERDISPLAYNAME            1121
#define IDC_STATS_TOTALTHREADSCREATED   1121
#define IDC_STATS_TOTALTHREADSCREATED2  1122
#define IDC_STATS_TOTALTHEAPMEMORYALLOCATED 1122
#define IDC_STATS_MAXHEAPALLOCATEDSIZE  1123
#define IDC_STATS_MAXHEAPALLOCATEDSIZE_STATIC 1124
#define IDC_PROGRESS                    1125
#define ID_SERVICE_TYPE                 1133
#define ID_SERVICE_START                1134
#define ID_SERVICE_ERROR                1135
#define ID_SERVICE_NAME                 1136
#define ID_SERVICE_CURRENT              1137
#define ID_SERVICE_DISPLAYNAME          1138
#define ID_SERVICE_IMAGEPATH            1139
#define ID_SERVICE_DESCRIPTION          1140
#define ID_SERVICE_DEPENDSONGROUP       1143
#define ID_SERVICE_LOADORDER            1144
#define ID_SERVICE_DEPENDSONSERVICE     1145
#define ID_SERVICE_DEPENDENTSERVICES    1146
#define ID_SERVICE_QUERYFAIL            1147
#define ID_SERVICE_TAG                  1148
#define ID_SERVICE_JUMPTOKEY            1149
#define ID_OBJECTDUMPERROR              1161
#define ID_OBJECDUMPHIDELABEL           1170
#define ID_PTL_CAPTION                  1234
#define ID_NAMESPACE_ROOT               1300
#define ID_NAMESPACE_ADDR               1301
#define ID_BDESCRIPTOR_ADDRESS          1302
#define ID_BDESCRIPTOR_NAME             1304
#define ID_BDESCRIPTOR_SID              1305
#define ID_BDESCRIPTOR_SID_ACCOUNT      1306
#define IDC_STATUS_TEXT                 1401
#define IDC_TIME_ELAPSED                1402
#define IDI_ICON_SORTUP                 6001
#define IDI_ICON_SORTDOWN               6002
#define ID_REGISTRYINFO                 7000
#define ID_REGISTRYDESC                 7001
#define ID_ABOUT_PROGRAM                11260
#define ID_ABOUT_BUILDDATE              11261
#define ID_ABOUT_OSNAME                 11262
#define ID_ABOUT_ADVINFO                11263
#define ID_ABOUT_OSNAME2                11264
#define ID_ABOUT_BUILDINFO              22011
#define ID_ABOUT_COMPILERINFO           22015
#define ID_FILE_EXIT                    40001
#define ID_FILE_RUNASADMIN              40002
#define ID_VIEW_REFRESH                 40003
#define ID_OBJECT_PROPERTIES            40004
#define ID_OBJECT_GOTOLINKTARGET        40005
#define ID_FIND_FINDOBJECT              40006
#define ID_HELP_ABOUT                   40007
#define ID_OBJECT_COPY                  40008
#define ID_ADDINFO_COPY                 40009
#define ID_HELP_HELP                    40016
#define ID_EXTRAS_PIPES                 40020
#define ID_EXTRAS_USERSHAREDDATA        40023
#define ID_EXTRAS_PRIVATENAMESPACES     40026
#define ID_EXTRAS_SSDT                  40030
#define ID_EXTRAS_DRIVERS               40033
#define ID_EXTRAS_MAILSLOTS             40036
#define ID_EXTRAS_W32PSERVICETABLE      40039
#define ID_EXTRAS_PROCESSLIST           40042
#define ID_EXTRAS_CALLBACKS             40043
#define ID_EXTRAS_SOFTWARELICENSECACHE  40044
#define ID_EXTRASCAPTION                40045
#define ID_OBJECTDUMPGROUPBOX           40046
#define ID_USDDUMPGROUPBOX              40047
#define ID_OBJECT_ICON                  40048
#define ID_HELP_SHOWLOG                 40049
#define ID_FILE_VIEW_PLUGINS            40050
#define ID_VIEW_DISPLAYGRID             40051
#define ID_VIEW_SECURITYDESCRIPTOR      40052
#define ID_JUMPTOFILE                   40053
#define ID_EXTRAS_UNLOADEDDRIVERS       40054
#define ID_EXTRAS_CMCONTROLVECTOR       40055
#define ID_VIEW_SYSINFO                 40057
#define ID_HELP_STATISTICS              40059
#define ID_OBJECT_COPY_NAME             40060
#define ID_OBJECT_COPY_NAME_BINARY      40061
#define ID_VIEW_LEGEND                  40062

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        279
#define _APS_NEXT_COMMAND_VALUE         40063
#define _APS_NEXT_CONTROL_VALUE         1400
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
